# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ba0d266f7334271847e7986c04d6d9e13f9015ad15ce188a5839f7ac39416053b05303cb0a8bdb5c8e4d9d277a01948e8c7808186e73c013818b57c80415076b

test:
  secret_key_base: 0a54540e2edee4aa30ec3814ca4ac6e4342e0a0ab999378b2420f4ee43b7c90bd718f6eff110b7ce7301adadd9699397a9d3b77d93297240f2fdc28381657660

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
